### ISSUE TITLE
Please make README

### ISSUE THREAD

**Issue by maksutovnurda** [ivanhrabcak/edupage-api#1]
Please make README

**Comment by ivanhrabcak** [comment]
I will add a README file documenting this library.

**Comment by maksutovnurda** [comment]
Thx!

**Comment by ivanhrabcak** [comment]
No problem! I added some information to the README. Let me know if anything is not documented well or missing so I can close this issue.

**Comment by ivanhrabcak** [comment]
Closing this issue!
