### ISSUE TITLE
Gramatická chyba v readme.

### ISSUE THREAD

**Issue by tomuisgod** [ivanhrabcak/edupage-api#11]
**Avaiable** je zle napísané. Správne to má byť **Available**
<img width="1072" alt="Snímka obrazovky 2021-03-29 o 12 26 28" src="https://user-images.githubusercontent.com/66744640/112823776-fdecb580-9089-11eb-93e9-e28345d97936.png">

**Comment by ivanhrabcak** [comment]
hahahhaha dakujem:D

**Comment by ivanhrabcak** [comment]
aj metoda je zle pomenovana:D

**Comment by tomuisgod** [comment]
Aj to no, nemáš zač. :)
