### ISSUE TITLE
Code from Readme not working

### ISSUE THREAD

**Issue by Pitak98** [ivanhrabcak/edupage-api#13]
So this code that i found in the readme does not work.
The error code:
  File "main.py", line 4, in <module>
    edupage.login()
  File "C:\Users\PeterKučera\AppData\Local\Programs\Python\Python38-32\lib\site-packages\edupage_api\__init__.py", line 31, in login
    csrf_token = csrf_response.split(
IndexError: list index out of range

I think it's because i am using python 3.8.5 32-bit.
Witch version of python i shoud use

I will include the code joust in case
`from edupage_api import Edupage

edupage = Edupage("Narniapk", "PeterKucera", "No looking on my password")  
edupage.login()

homework = edupage.get_homework()

for hw in homework:
    print(hw.due_date)`

**Comment by BelKed** [comment]
```python
edupage = Edupage("Narniapk", "PeterKucera", "No looking on my password")
```

It seems like link to your school "Narniapk" (https://Narniapk.edupage.org) does not exist. Your school have homepage at https://www.narniapk.sk, but EduPage login page is at https://czsnarniapk.edupage.org. So, you should use "czsnarniapk":
```python
edupage = Edupage("czsnarniapk", "PeterKucera", "No looking on my password")
```

**Comment by Pitak98** [comment]
Thanks that worked sorry for confusion.
