### ISSUE TITLE
[Feature request] Filter done in forloops

### ISSUE THREAD

**Issue by Pitak98** [ivanhrabcak/edupage-api#17]
Is there any way to filter done homeworks in forloops (code bellow)?

**for hw in homework:
    print(hw.due_date)
    print(hw.title)
    print(hw.description)**

If not could you add it?

**Comment by ivanhrabcak** [comment]
Ok, I can implement it when I have time, at the same time as #9

**Comment by Pitak98** [comment]
Thank you!

**Comment by ivanhrabcak** [comment]
Now that notifications are implemented, you can do this.

I am going to publish this feature to pip, but expect changes; I think there are improvements to be made. If you are satisfied on how this feature works, please reply so I can close this issue.

**Comment by Pitak98** [comment]
I did not figure it out how to do it (I am not good with python) plese coud you send me an example?

**Comment by ivanhrabcak** [comment]
Sorry, it isn't documented yet. 
```python
from edupage_api import Edupage, NotificationType

edupage = Edupage("subdomain", "username", "password")
edupage.login()

notifications = edupage.get_notifications()
for notification in notifications:
    if notification.event_type == NotificationType.HOMEWORK:
        print(f"{str(notification.due_date)=}")
        print(f"{notification.name=}")
        print("--------------------")
```
You also have access to other properties, that are not specific to homework like:
```python
# ...
print(notification.recipient)
print(notification.date_added)
print(notification.author)
```
