### ISSUE TITLE
[Feature request] Get attachments (files) attached to homework

### ISSUE THREAD

**Issue by cfpwastaken** [ivanhrabcak/edupage-api#18]
**Is your feature request related to a problem? Please describe.**
It would be cool if you could get the files attached to homework.
For example, this could make a script automatically printing homework.

**Describe the solution you'd like**
For example
`homework.getAttachment(0)` gets the first Attachment of an EduHomework object.

**Comment by ivanhrabcak** [comment]
I can't see the attached files in the homework assignment (that's how it works right now), this would require me to create a MaterialData parser (which can also parse tests).
This is a lot of work, but it is planned

**Comment by ivanhrabcak** [comment]
This is now supported (but not tested)! If this feature works for you, please reply so I can close this issue.
