### ISSUE TITLE
The ShortLook Code, have you download it to the local?

### ISSUE THREAD

**Issue by SnailTheDev** [ivanhrabcak/edupage-api#28]
Hi, I am an iOS Reverse Dev. I see you had forked my source SnailTheDev/ShortLook, but the author offline the repository, if you ever download the source code locally, would like to beg you to share a copy, contact me  with  mu514983786@gmail.com.

**Comment by ivanhrabcak** [comment]
Hello, unfortunately I do not have a copy of the source code locally. I thought it was the original source/the tweak has been opensourced because it's free. If you wish to contact me, can you do so on my e-mail (ivan@hrabcak.eu)?
