### ISSUE TITLE
[Error] Error with edupage.get_timetable.

### ISSUE THREAD

**Issue by ltlklr** [ivanhrabcak/edupage-api#29]
The "Login" example works fine, I get no errors, but when I try to use the "Get the timetable for a date" example I get this error:

```
  File "C:\Users\L-hub\Desktop\Bot\Bot.py", line 7, in <module>
    timetable = edupage.get_timetable(today) # returns EduTimetable
  File "C:\Program Files\Python36\lib\site-packages\edupage_api\__init__.py", line 118, in get_timetable
    subject_name = self.ids.id_to_subject(subject_id)
  File "C:\Program Files\Python36\lib\site-packages\edupage_api\utils.py", line 61, in id_to_subject
    return self.dbi.get("subjects").get(s_id).get("short")
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by ltlklr** [comment]
`print(edupage.data.get("dbi") == None)` Returns False.

**Comment by ivanhrabcak** [comment]
I'll add better logging to resolve help us resolve this issue, than you can send the log so we can look at what went wrong.

**Comment by ltlklr** [comment]
Running `print(edupage.data.get("dbi"))` returns alot of (I changed the name and the ID of the teacher to not mention real names and ID's.):
{'teachers': {'-21313452435': {'id': '-21313452435', 'firstname': 'Adfgsdfg', 'lastname': 'sfgdgsdfg', 'short': 'sfgsdfgdsfg', 'gender': 'F', 'classroomid': '', 'datefrom': '', 'dateto': '', 'isOut': False},

**Comment by BelKed** [comment]
> Running `print(edupage.data.get("dbi"))` returns alot of (I changed the name and the ID of the teacher to not mention real names and ID's.):
> {'teachers': {'-21313452435': {'id': '-21313452435', 'firstname': 'Adfgsdfg', 'lastname': 'sfgdgsdfg', 'short': 'sfgsdfgdsfg', 'gender': 'F', 'classroomid': '', 'datefrom': '', 'dateto': '', 'isOut': False},

`print(edupage.data.get("dbi"))` returns teachers, students and subjects.
For getting timetable, use `print(edupage.data.get("dp"))`. It should return JSON object in that format:

![Timetable format](https://user-images.githubusercontent.com/66956532/134398404-aec87484-9c99-4f7b-ad26-49e580a58251.png)

**Comment by ltlklr** [comment]
I do get some information, but its hard to see. How do you get the nice view?

**Comment by ivanhrabcak** [comment]
You can put it in a formatter like https://jsonformatter.org/json-pretty-print or use the `pprint` library.

**Comment by ltlklr** [comment]
`print(edupage.data.get("dpi"))` returns None. But `print(edupage.data.get("dp"))` returns a JSON. Thanks for the formatter. One more question is there an easy way to translate subjectID to the actual name of the subject?

**Comment by ivanhrabcak** [comment]
Hello, I've added logging in [0.9.85](https://github.com/ivanhrabcak/edupage-api/releases/tag/0.9.85)!
If you edit your code to intialize your edupage object like this:
```python
from edupage_api import LogLevel

edupage = Edupage("subdomain", "username", "password", log_level=LogLevel.DEBUG)
```
It will print additional debug info. If you could show the console output, we could resolve this issue.

**Comment by ivanhrabcak** [comment]
Closing this issue, please comment here if you experience it.

**Comment by javokhirkasimov** [comment]
Guys I've been trying to get timetable data for long time, and have the same issue. However 

> > Running `print(edupage.data.get("dbi"))` returns alot of (I changed the name and the ID of the teacher to not mention real names and ID's.):
> > {'teachers': {'-21313452435': {'id': '-21313452435', 'firstname': 'Adfgsdfg', 'lastname': 'sfgdgsdfg', 'short': 'sfgsdfgdsfg', 'gender': 'F', 'classroomid': '', 'datefrom': '', 'dateto': '', 'isOut': False},
> 
> `print(edupage.data.get("dbi"))` returns teachers, students and subjects. For getting timetable, use `print(edupage.data.get("dp"))`. It should return JSON object in that format:
> 
> ![Timetable format](https://user-images.githubusercontent.com/66956532/134398404-aec87484-9c99-4f7b-ad26-49e580a58251.png)

I have the same issue but `print(edupage.data.get("dp"))` is returning empty list, what can be the problem?

**Comment by BelKed** [comment]
Which version of the `edupage-api` library are you using? Is it the latest one ([`0.10.1`](https://github.com/ivanhrabcak/edupage-api/releases/tag/0.10.1))?

Also, what does your whole code look like?
