### ISSUE TITLE
[Feature request] Exam support

### ISSUE THREAD

**Issue by KexoTV** [ivanhrabcak/edupage-api#30]
**Please add exams support**
Then edupage-api would return subject name, teacher's name, exam description and exam day.
![image](https://user-images.githubusercontent.com/55331891/134353104-b1a77073-6cb2-4c12-8e25-ad3f2d617a1d.png)

**Comment by BelKed** [comment]
I think, it can be done thought `edupage.get_notifications()`...

Exams have typ `NotificationType.EVENT`. But this type have multiple events – also holiday, distance eduation, ... Name of the event is saved in `event_type_name`, so you could filter by it...

More info about `EduNotification`: https://github.com/ivanhrabcak/edupage-api#edunotification.

**Comment by ivanhrabcak** [comment]
This is now supported with `additional_data`!
