### ISSUE TITLE
disable empty type in notifications

### ISSUE THREAD

**Issue by Kubk0** [ivanhrabcak/edupage-api#35]
Is there a way that i can disable the "[WARNING] Found notification with empty type, skipping..." messages and still get the text of the notification?

**Comment by ivanhrabcak** [comment]
You can pass the `log_level` argument when creating the `Edupage` object like this:
```python
from edupage import LogLevel

# ...

edupage = Edupage("school", "username", "password", log_level = LogLevel.NONE)
```
This will disable all logging by edupage_api

**Comment by Kubk0** [comment]
Can i still get the notificarion text if i disable just the logging?

**Comment by BelKed** [comment]
Yes, you can. `log_level=LogLevel.NONE` disables `DEBUG`, `WARNING` and `ERROR` messages from `edupage-api`, and it doesn't influence other behaviour.
