### ISSUE TITLE
[Feature request] Examples

### ISSUE THREAD

**Issue by peterkisak** [ivanhrabcak/edupage-api#39]
**Is your feature request related to the issue? Describe.**
I don't know the current version

**Describe the solution you would like**
I would like to be added examples of how to use it as it was before.
since what was already no longer works

**Comment by BelKed** [comment]
If you are using version `0.9.88` or older, [here](https://github.com/ivanhrabcak/edupage-api/blob/12c60b67d288ace4bdb9f4ea3e37768f898248a0/README.md#usage) are the examples.
Some of them may work also for the latest version (`0.9.9`).

I will write examples for the latest version during the next week...

**Comment by peterkisak** [comment]
the old version was better for me. the new one is too complicated

**Comment by peterkisak** [comment]
and how can I use the old version?

**Comment by BelKed** [comment]
I think, you're still using the old version, because the latest one (`0.9.9`) is not published on [PyPi](https://pypi.org/project/edupage-api/).

You can check version of `edupage-api` by running command `pip show edupage-api`. It should output something like this:
```
❯ pip show edupage-api
Name: edupage-api
Version: 0.9.88
Summary: A python library for accessing your Edupage account
Home-page: https://github.com/ivanhrabcak/edupage-api
Author: ivanhrabcak
Author-email: ivan@hrabcak.eu
License: UNKNOWN
Location: /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages
Requires: requests
Required-by: 
```

**Comment by ivanhrabcak** [comment]
Hello, I am currently working on some basic examples with the new 0.9.9 version, I will push them one by one in the next 30 minutes - 2 hours.

**Comment by peterkisak** [comment]
thank you very much and I need an example for lunch the most

**Comment by ivanhrabcak** [comment]
I've added an example for homework (notifications in general) and I am working on the lunch example.

**Comment by ivanhrabcak** [comment]
I've added the lunch example, closing. (I will be adding more this week)
