### ISSUE TITLE
[Bug] code is >python3.9, but pip still downloads non-functional versio for 3.8

### ISSUE THREAD

**Issue by Chaos99** [ivanhrabcak/edupage-api#41]
**Describe the bug**
With Python 3.8, pip will download a version of this library that is not up to date and non-functional

**Expected behavior**
If you no longer support 3.8 (I assume so, as you current version is >3.9), remove the pip package for 3.8 and older.
Maybe place a note in your readme about the minimum Python version.

**Comment by ivanhrabcak** [comment]
I thought maybe pip would at least give a warning when you install it:(. Thank you for reminding me! I've added a warning to the readme.

The python version is already on multiple places, but somehow nothings stops you from installing the package on lower python versions. 

![image](https://user-images.githubusercontent.com/39710116/152636764-dc5c8543-eac7-473d-8c39-109e443ad02b.png)
