### ISSUE TITLE
[Bug] `Grades.get_grades` - max_points doesn't work

### ISSUE THREAD

**Issue by ivanhrabcak** [ivanhrabcak/edupage-api#43]
**Describe the bug**
When I was writing the grades example, I found out `get_grades` is not working properly.
For me, the max points are never in `p_vaha_body`, they sometimes show up in `p_vaha`.

**How to reproduce**
```python
# ...login

grades = edupage.get_grades()
for grade in grades:
    print(grade.max_points)
```

**Expected behavior**
Every grade (except grades with percentages) should have `max_points`, but `max_points` is `None`

**Version**
- Edupage API version: **latest commit**

**The bug**
The code with the bug is [here](https://github.com/ivanhrabcak/edupage-api/blob/5f861bd27a67ee8e3aaac4fe667a662198973663/edupage_api/grades.py#L82).

Could anyone else test this? Where are the max points for you? (Are they in `p_vaha`?)

**Comment by BelKed** [comment]
If I understand correctly, how EduPage works, grades are differentiated by `p_typ_udalosti`:
- `1` –> Normal grades (1 – 5)
- `2` –> Points grades (in points, e.g. 0 – 20 points)
- `3` –> Percentage grades (0 – 100 %)

So, according to this knowledge, I implemented that in https://github.com/ivanhrabcak/edupage-api/commit/1acdf1b0659e6473ca1f02a53a286e3b892a9ccc.
I hope, it will work now correctly...

**Comment by ivanhrabcak** [comment]
Good job! Everything is working properly now.
