### ISSUE TITLE
LoginDataParsingException [Bug] 

### ISSUE THREAD

**Issue by vlckoadam** [ivanhrabcak/edupage-api#47]
**Describe the bug**
LDPE (exception, nie plast) Asi si Edupage trocha prekopal kód. 

**Your code**
Obyčajný `edupage.login()`
Credentials v konštruktori sú ok _(mohla by sa aktualizovať dokumentácia btw, tam sú furt v `login()`)_, subdoména existuje. Do 11:00 to šlapalo. 

**Error message**
```
Traceback (most recent call last):
  File "C:\Users\pc\AppData\Local\Programs\Python\Python38-32\lib\site-packages\edupage_api\__init__.py", line 57, in login
    self.parse_login_data(response.content.decode())
  File "C:\Users\pc\AppData\Local\Programs\Python\Python38-32\lib\site-packages\edupage_api\__init__.py", line 64, in parse_login_data
    js_json = data.split("$j(document).ready(function() {")[1] \
IndexError: list index out of range
```

**Version**
- Edupage API version: **0.9.3**
- Python version: **3.8.3**

**Comment by BelKed** [comment]
Unfortunately, I can't reproduce this behaviour in the latest version (`0.9.981`). I think it was already fixed in this commit: https://github.com/ivanhrabcak/edupage-api/commit/a975c65fca05cc274539daec972d5c50ed6994c2
Please try upgrading to this version and try running your code again...

**Comment by vlckoadam** [comment]
Ok. Updating helped. Thanks.
