### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by abdulhamidll** [ivanhrabcak/edupage-api#58]
**Describe the bug**

**Your code**
```python
Add here your code with bug...
```

**Error message**
```
Add here your error message (traceback)
```

**Expected behavior**

**Version**
- Edupage API version: **(e.g. 0.9.6)**
- Python version: **(e.g. 3.7.1)**

**Comment by abdulhamidll** [comment]
dp is empty

**Comment by ivanhrabcak** [comment]
Could you describe the issue further? Maybe give the code that gives you the error? Could you send the exact error that you get?
