### ISSUE TITLE
Error with edupage.login()

### ISSUE THREAD

**Issue by tim-py399** [ivanhrabcak/edupage-api#6]
When i use `edupage.login` as showed in the documentation, it gives me this Error Message:

```
Exception has occurred: JSONDecodeError
Unterminated string starting at: line 1 column 130169 (char 130168)

```
My code:
```
from edupage_api import Edupage

edupage = Edupage(my_username, my_password)
edupage.login()
```

Is that because I use it wrong?

**Comment by ivanhrabcak** [comment]
What is your main language? Do you have any special characters in your language? Does this happen 100% of the time?

This is probably an issue with my code.

**Comment by tim-py399** [comment]
i'm from germany, yes, we have ä, ö, ü and ß, and i happens 100% of the time

**Comment by tim-py399** [comment]
the type Error it gives out is: 

`Object of type TextIOWrapper is not JSON serializable`

**Comment by ivanhrabcak** [comment]
That's probably because you've got the order wrong.
```python3
with open("js.json", "w") as f:
    json.dump(f, js_json, indent=4)

```
should be
```python3
with open("js.json", "w") as f:
    json.dump(js_json, f, indent=4)
```

**Comment by ivanhrabcak** [comment]
Do you see any json in the response? If so, what is before it?

**Comment by tim-py399** [comment]
yes, it gives out a json file. What do you mean with "whats before it"

**Comment by ivanhrabcak** [comment]
The response variable contains a html document that was fetched from Edupage. If you look at the beginning and scroll down where the json begins, you can see what's before it.

**Comment by tim-py399** [comment]
I'm sorry i still dont understand what you mean by the beginning, and whats before the beginning,
you mean the beginning of the json file, right?

but if you're on the python discord server, we could go in a voice chat and you could explain it to me

**Comment by ivanhrabcak** [comment]
Yes, that would be perfect. Can you drop a invite to the discord server here?

**Comment by tim-py399** [comment]
the python server wants you to have send at least 50 messages before it lets you speak, so i just made a new server for us: https://discord.gg/cQSPeRUtVG

if you still want to join the python discord server here's the link: https://discord.gg/python

**Comment by ivanhrabcak** [comment]
Unfortunately, I can't find the cause of this issue... If anyone else experiences this, please comment here

**Comment by tim-py399** [comment]
Thank you for trying!

**Comment by ivanhrabcak** [comment]
Hello, I've added a new way of logging in. Can you try and see if this issue is fixed for you?

**Comment by tim-py399** [comment]
yessir, it works! absolutely amazing, thank you very much for your effort!

**Comment by ivanhrabcak** [comment]
Glad to hear that!
