### ISSUE TITLE
[Feature request]  ASC smartbox api

### ISSUE THREAD

**Issue by oguh43** [ivanhrabcak/edupage-api#60]
Aplikácia https://apkgk.com/sk/sk.asc.ascdisplay/download sa dá decompilnúť a nie je obfuskovaná. Sú tam gemy ako default heslá v stringu a ich api.
príklady:
https://gymbilba.edupage.org/connect_entrance.php?device_list
https://connect.edupage.org/connect_entrance.php?verify_edupage=gymbilba
https://gymbilba.edupage.org/connect_entrance.php?get_device_to_display=
heslo: 3w79b65Q4kdZ68n

**Comment by ivanhrabcak** [comment]
Hello, I don't think this API is in scope of this library.
