### ISSUE TITLE
[Bug] Cannot use send_message (Edupage or Messages class - same)

### ISSUE THREAD

**Issue by Nexusatko** [ivanhrabcak/edupage-api#62]
**Describe the bug**
When I try to send any message to any classmate/person, it gives me an error pasted below.

**Your code**
```python
from edupage_api import Edupage
from edupage_api.messages import Messages
from edupage_api.people import People
import datetime
import edupage_api
edupage = Edupage()
message = Messages(edupage)
ppl = People(edupage)
edupage.login_auto("better","not")
classmate = ppl.get_student(int(hidden-int-for-github-xd))

edupage.send_message(classmate,str("Test message"))

```

**Error message**
```
  File "C:\Users\nexus\AppData\Local\Programs\Python\Python311\Lib\site-packages\edupage_api\__init__.py", line 102, in send_message
    return Messages(self).send_message(recipients, body)
  File "C:\Users\nexus\AppData\Local\Programs\Python\Python311\Lib\site-packages\edupage_api\messages.py", line 47, in send_message
    raise RequestError("Failed to send message (edupage returned an empty 'changes' array)")
edupage_api.exceptions.RequestError: Failed to send message (edupage returned an empty 'changes' array)
```

**Expected behaviour**
Umm, no error? :D 

**Version**
- Edupage API version: **0.10.2**
- Python version: **3.11**

**Comment by ivanhrabcak** [comment]
We keep the issues in english, as there are also users that do not speak Slovak.

Does the message get sent?

**Comment by Nexusatko** [comment]
No, it's not showing in history of conversation with that person.

**Comment by ivanhrabcak** [comment]
I think the issue is in `EduAccount.get_id`.

I want you to compare the numbers from your and your classmate's userId:
Example: 
You: `Student971239`, your classmate `Student971139`

Is the positivity of both numbers the same? (Here, both numbers are positive, if one would be negative, that would be bad.)
Is your number above zero?
Is your classmate's number above zero?

Thank you for your cooperation.

**Comment by Nexusatko** [comment]
All IDs are correct and non-negative. I copied them from Edupage.get_students method. 
Even if I use print(classmate) it prints the correct classmate and info about him/her.

**Comment by ivanhrabcak** [comment]
Does it also match `Edupage.get_my_id`?

**Comment by Nexusatko** [comment]
It's Edupage.get_user_id() but yes, ID matches. Even though it outputs as StudentID_HERE and not as ID_HERE when I use Edupage.get_user_id() but I assume that's correct.

**Comment by ivanhrabcak** [comment]
Could we get on discord to resolve the issue?

https://discord.gg/fg6zBu9ZAn

**Comment by ivanhrabcak** [comment]
The issue is in the difference in `Student` and `StudentOnly`. @Nexusatko cannot send messages to the `Student` user (which includes the student's parents), only to the `StudentOnly` one.

I will add a new account type - `StudentOnly`.
