### ISSUE TITLE
Is the API legal to use?

### ISSUE THREAD

**Issue by Bobrokus** [ivanhrabcak/edupage-api#67]
Is the API legal to use? https://www.edupage.org/gdpr/

**Comment by BelKed** [comment]
As far as I know, and from my perspective, I believe it is legal to use.
Would you mind specifying which aspect of the GDPR you are concerned about?

**Comment by Bobrokus** [comment]
> As far as I know, and from my perspective, I believe it is legal to use. Would you mind specifying which aspect of the GDPR you are concerned about?

I don't know if the article has to do anything with it. I was concerned that there might be some legal issues with using this API.
I attached the article, just so you can check it out to be sure. If you are confident, that it's safe to use. I would be happy to use it.

**Comment by Bobrokus** [comment]
Mimochodom, trochu od veci. Ale teraz som zistil, ze ste tiez slovak. Takze ani neviem preco som rozpraval po anglicky. Tak to poviem aj v slovencine.

Nie som si isty ci ten clanok ma nieco spolocne s tym ci je to legalne pouzivat. Prilozil som ho len pre istotu. Ak ste si isty, ze je to bezpecne na pouzivanie, tak budem rad.

**Comment by BelKed** [comment]
If you want to be 100% safe, I recommend you to use the official EduPage API :)

And, by the way, we would prefer to keep it English there since more people speak English than Slovak.

**Comment by Bobrokus** [comment]
> If you want to be 100% safe, I recommend you to use the official EduPage API :)
> 
> And, by the way, we would prefer to keep it English there since more people speak English than Slovak.

Which one? I can't find any official Edupage API

**Comment by BelKed** [comment]
For information about the official API, I recommend you to contact aSc Agenda/EduPage directly.
Please note, you would need a token from your school to use the API.

**Comment by Bobrokus** [comment]
> Please note, you would need a token from your school to use the API.

In that case I would rather use this one .

**Comment by BelKed** [comment]
Cool!
If you have no further questions, feel free to close this issue :)
