### ISSUE TITLE
[Feature request] Get grades from a previous school term

### ISSUE THREAD

**Issue by goodbyepavlyi** [ivanhrabcak/edupage-api#68]
I have noticed that the EduPage.get_grades() function allows for obtaining all grades, but it is limited to providing grades for the current school term only. Is there a possibility to access grades from previous school terms?

**Comment by goodbyepavlyi** [comment]
I think I found the solution to this in PR #69.

**Comment by ivanhrabcak** [comment]
Thank you! Added in [0.10.5](https://github.com/ivanhrabcak/edupage-api/releases/tag/0.10.5).

You can run:
```shell
$ pip install --upgrade edupage-api
```
To upgrade to the new version and use this feature.
