### ISSUE TITLE
Where I can write school name?

### ISSUE THREAD

**Issue by maksutovnurda** [ivanhrabcak/edupage-api#8]
For example what if my school:  exampleschool.edupage.org.

**Comment by ivanhrabcak** [comment]
The school name is pulled out from the response of the login request. I am not sure if it works for all schools though...
```python3
self.school = response.url.split(".edupage.org")[0].split("https://")[1]
```
Does it not work for you? If so, @freegamerskids provided a pretty good solution, but you have to enter the school name manually

**Comment by maksutovnurda** [comment]
> enter the school name manually

Thanks, I figured it, didn't notice that I need to enter school name manually
